CC      = g++
CFLAGS  = -Ofast -W -Wall -Wextra -DNDEBUG
DEPS    = headers/Class.hpp headers/Methods.hpp

ASOURCES = AIRSS.cpp $(DEPS:.hpp=.cpp)
AOBJ = $(ASOURCES:.cpp=.o)

GSOURCES = Gabrielle.cpp $(DEPS:.hpp=.cpp)
GOBJ = $(GSOURCES:.cpp=.o)

MSOURCES = Map.cpp $(DEPS:.hpp=.cpp)
MOBJ = $(MSOURCES:.cpp=.o)



%.o: %.c $(DEPS)
	$(CC) -c -o $@ $< $(CFLAGS)

Map: $(MOBJ)
	makedepend $(MSOURCES)
	$(CC) -o ../$@ $(MOBJ) $(CFLAGS)

AIRSS: $(AOBJ)
	makedepend $(ASOURCES)
	$(CC) -o ../$@ $(AOBJ) $(CFLAGS)

Gabrielle: $(GOBJ)
	makedepend $(GSOURCES)
	$(CC) -o ../$@ $(GOBJ) $(CFLAGS)

Sim:
	make AIRSS
	make Gabrielle
	make Map

clean:
	rm -f ∗~ $(MOBJ) $(AOBJ) $(GOBJ) ∗.bak

# DO NOT DELETE

Gabrielle.o: headers/Methods.hpp headers/Class.hpp headers/Eigen/Dense
Gabrielle.o: headers/Eigen/Core
Gabrielle.o: headers/Eigen/src/Core/util/DisableStupidWarnings.h
Gabrielle.o: headers/Eigen/src/Core/util/Macros.h
Gabrielle.o: headers/Eigen/src/Core/util/MKL_support.h
Gabrielle.o: headers/Eigen/src/Core/util/Constants.h
Gabrielle.o: headers/Eigen/src/Core/util/Meta.h
Gabrielle.o: headers/Eigen/src/Core/util/ForwardDeclarations.h
Gabrielle.o: headers/Eigen/src/Core/util/StaticAssert.h
Gabrielle.o: headers/Eigen/src/Core/util/XprHelper.h
Gabrielle.o: headers/Eigen/src/Core/util/Memory.h
Gabrielle.o: headers/Eigen/src/Core/NumTraits.h
Gabrielle.o: headers/Eigen/src/Core/MathFunctions.h
Gabrielle.o: headers/Eigen/src/Core/GenericPacketMath.h
Gabrielle.o: headers/Eigen/src/Core/MathFunctionsImpl.h
Gabrielle.o: headers/Eigen/src/Core/arch/Default/ConjHelper.h
Gabrielle.o: headers/Eigen/src/Core/arch/CUDA/Half.h
Gabrielle.o: headers/Eigen/src/Core/arch/CUDA/PacketMathHalf.h
Gabrielle.o: headers/Eigen/src/Core/arch/CUDA/TypeCasting.h
Gabrielle.o: headers/Eigen/src/Core/arch/Default/Settings.h
Gabrielle.o: headers/Eigen/src/Core/functors/TernaryFunctors.h
Gabrielle.o: headers/Eigen/src/Core/functors/BinaryFunctors.h
Gabrielle.o: headers/Eigen/src/Core/functors/UnaryFunctors.h
Gabrielle.o: headers/Eigen/src/Core/functors/NullaryFunctors.h
Gabrielle.o: headers/Eigen/src/Core/functors/StlFunctors.h
Gabrielle.o: headers/Eigen/src/Core/functors/AssignmentFunctors.h
Gabrielle.o: headers/Eigen/src/Core/arch/CUDA/Complex.h
Gabrielle.o: headers/Eigen/src/Core/IO.h
Gabrielle.o: headers/Eigen/src/Core/DenseCoeffsBase.h
Gabrielle.o: headers/Eigen/src/Core/DenseBase.h
Gabrielle.o: headers/Eigen/src/plugins/BlockMethods.h
Gabrielle.o: headers/Eigen/src/Core/MatrixBase.h
Gabrielle.o: headers/Eigen/src/plugins/CommonCwiseUnaryOps.h
Gabrielle.o: headers/Eigen/src/plugins/CommonCwiseBinaryOps.h
Gabrielle.o: headers/Eigen/src/plugins/MatrixCwiseUnaryOps.h
Gabrielle.o: headers/Eigen/src/plugins/MatrixCwiseBinaryOps.h
Gabrielle.o: headers/Eigen/src/Core/EigenBase.h
Gabrielle.o: headers/Eigen/src/Core/Product.h
Gabrielle.o: headers/Eigen/src/Core/CoreEvaluators.h
Gabrielle.o: headers/Eigen/src/Core/AssignEvaluator.h
Gabrielle.o: headers/Eigen/src/Core/Assign.h
Gabrielle.o: headers/Eigen/src/Core/ArrayBase.h
Gabrielle.o: headers/Eigen/src/plugins/ArrayCwiseUnaryOps.h
Gabrielle.o: headers/Eigen/src/plugins/ArrayCwiseBinaryOps.h
Gabrielle.o: headers/Eigen/src/Core/util/BlasUtil.h
Gabrielle.o: headers/Eigen/src/Core/DenseStorage.h
Gabrielle.o: headers/Eigen/src/Core/NestByValue.h
Gabrielle.o: headers/Eigen/src/Core/ReturnByValue.h
Gabrielle.o: headers/Eigen/src/Core/NoAlias.h
Gabrielle.o: headers/Eigen/src/Core/PlainObjectBase.h
Gabrielle.o: headers/Eigen/src/Core/Matrix.h headers/Eigen/src/Core/Array.h
Gabrielle.o: headers/Eigen/src/Core/CwiseTernaryOp.h
Gabrielle.o: headers/Eigen/src/Core/CwiseBinaryOp.h
Gabrielle.o: headers/Eigen/src/Core/CwiseUnaryOp.h
Gabrielle.o: headers/Eigen/src/Core/CwiseNullaryOp.h
Gabrielle.o: headers/Eigen/src/Core/CwiseUnaryView.h
Gabrielle.o: headers/Eigen/src/Core/SelfCwiseBinaryOp.h
Gabrielle.o: headers/Eigen/src/Core/Dot.h headers/Eigen/src/Core/StableNorm.h
Gabrielle.o: headers/Eigen/src/Core/Stride.h headers/Eigen/src/Core/MapBase.h
Gabrielle.o: headers/Eigen/src/Core/Map.h headers/Eigen/src/Core/Ref.h
Gabrielle.o: headers/Eigen/src/Core/Block.h
Gabrielle.o: headers/Eigen/src/Core/VectorBlock.h
Gabrielle.o: headers/Eigen/src/Core/Transpose.h
Gabrielle.o: headers/Eigen/src/Core/DiagonalMatrix.h
Gabrielle.o: headers/Eigen/src/Core/Diagonal.h
Gabrielle.o: headers/Eigen/src/Core/DiagonalProduct.h
Gabrielle.o: headers/Eigen/src/Core/Redux.h headers/Eigen/src/Core/Visitor.h
Gabrielle.o: headers/Eigen/src/Core/Fuzzy.h headers/Eigen/src/Core/Swap.h
Gabrielle.o: headers/Eigen/src/Core/CommaInitializer.h
Gabrielle.o: headers/Eigen/src/Core/GeneralProduct.h
Gabrielle.o: headers/Eigen/src/Core/Solve.h headers/Eigen/src/Core/Inverse.h
Gabrielle.o: headers/Eigen/src/Core/SolverBase.h
Gabrielle.o: headers/Eigen/src/Core/PermutationMatrix.h
Gabrielle.o: headers/Eigen/src/Core/Transpositions.h
Gabrielle.o: headers/Eigen/src/Core/TriangularMatrix.h
Gabrielle.o: headers/Eigen/src/Core/SelfAdjointView.h
Gabrielle.o: headers/Eigen/src/Core/products/GeneralBlockPanelKernel.h
Gabrielle.o: headers/Eigen/src/Core/products/Parallelizer.h
Gabrielle.o: headers/Eigen/src/Core/ProductEvaluators.h
Gabrielle.o: headers/Eigen/src/Core/products/GeneralMatrixVector.h
Gabrielle.o: headers/Eigen/src/Core/products/GeneralMatrixMatrix.h
Gabrielle.o: headers/Eigen/src/Core/SolveTriangular.h
Gabrielle.o: headers/Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h
Gabrielle.o: headers/Eigen/src/Core/products/SelfadjointMatrixVector.h
Gabrielle.o: headers/Eigen/src/Core/products/SelfadjointMatrixMatrix.h
Gabrielle.o: headers/Eigen/src/Core/products/SelfadjointProduct.h
Gabrielle.o: headers/Eigen/src/Core/products/SelfadjointRank2Update.h
Gabrielle.o: headers/Eigen/src/Core/products/TriangularMatrixVector.h
Gabrielle.o: headers/Eigen/src/Core/products/TriangularMatrixMatrix.h
Gabrielle.o: headers/Eigen/src/Core/products/TriangularSolverMatrix.h
Gabrielle.o: headers/Eigen/src/Core/products/TriangularSolverVector.h
Gabrielle.o: headers/Eigen/src/Core/BandMatrix.h
Gabrielle.o: headers/Eigen/src/Core/CoreIterators.h
Gabrielle.o: headers/Eigen/src/Core/ConditionEstimator.h
Gabrielle.o: headers/Eigen/src/Core/BooleanRedux.h
Gabrielle.o: headers/Eigen/src/Core/Select.h
Gabrielle.o: headers/Eigen/src/Core/VectorwiseOp.h
Gabrielle.o: headers/Eigen/src/Core/Random.h
Gabrielle.o: headers/Eigen/src/Core/Replicate.h
Gabrielle.o: headers/Eigen/src/Core/Reverse.h
Gabrielle.o: headers/Eigen/src/Core/ArrayWrapper.h
Gabrielle.o: headers/Eigen/src/Core/GlobalFunctions.h
Gabrielle.o: headers/Eigen/src/Core/util/ReenableStupidWarnings.h
Gabrielle.o: headers/Eigen/LU headers/Eigen/src/misc/Kernel.h
Gabrielle.o: headers/Eigen/src/misc/Image.h headers/Eigen/src/LU/FullPivLU.h
Gabrielle.o: headers/Eigen/src/LU/PartialPivLU.h
Gabrielle.o: headers/Eigen/src/LU/Determinant.h
Gabrielle.o: headers/Eigen/src/LU/InverseImpl.h headers/Eigen/Cholesky
Gabrielle.o: headers/Eigen/Jacobi headers/Eigen/src/Jacobi/Jacobi.h
Gabrielle.o: headers/Eigen/src/Cholesky/LLT.h
Gabrielle.o: headers/Eigen/src/Cholesky/LDLT.h headers/Eigen/QR
Gabrielle.o: headers/Eigen/Householder
Gabrielle.o: headers/Eigen/src/Householder/Householder.h
Gabrielle.o: headers/Eigen/src/Householder/HouseholderSequence.h
Gabrielle.o: headers/Eigen/src/Householder/BlockHouseholder.h
Gabrielle.o: headers/Eigen/src/QR/HouseholderQR.h
Gabrielle.o: headers/Eigen/src/QR/FullPivHouseholderQR.h
Gabrielle.o: headers/Eigen/src/QR/ColPivHouseholderQR.h
Gabrielle.o: headers/Eigen/src/QR/CompleteOrthogonalDecomposition.h
Gabrielle.o: headers/Eigen/SVD headers/Eigen/src/misc/RealSvd2x2.h
Gabrielle.o: headers/Eigen/src/SVD/UpperBidiagonalization.h
Gabrielle.o: headers/Eigen/src/SVD/SVDBase.h
Gabrielle.o: headers/Eigen/src/SVD/JacobiSVD.h headers/Eigen/src/SVD/BDCSVD.h
Gabrielle.o: headers/Eigen/Geometry headers/Eigen/src/Geometry/OrthoMethods.h
Gabrielle.o: headers/Eigen/src/Geometry/EulerAngles.h
Gabrielle.o: headers/Eigen/src/Geometry/Homogeneous.h
Gabrielle.o: headers/Eigen/src/Geometry/RotationBase.h
Gabrielle.o: headers/Eigen/src/Geometry/Rotation2D.h
Gabrielle.o: headers/Eigen/src/Geometry/Quaternion.h
Gabrielle.o: headers/Eigen/src/Geometry/AngleAxis.h
Gabrielle.o: headers/Eigen/src/Geometry/Transform.h
Gabrielle.o: headers/Eigen/src/Geometry/Translation.h
Gabrielle.o: headers/Eigen/src/Geometry/Scaling.h
Gabrielle.o: headers/Eigen/src/Geometry/Hyperplane.h
Gabrielle.o: headers/Eigen/src/Geometry/ParametrizedLine.h
Gabrielle.o: headers/Eigen/src/Geometry/AlignedBox.h
Gabrielle.o: headers/Eigen/src/Geometry/Umeyama.h headers/Eigen/Eigenvalues
Gabrielle.o: headers/Eigen/src/Eigenvalues/Tridiagonalization.h
Gabrielle.o: headers/Eigen/src/Eigenvalues/RealSchur.h
Gabrielle.o: headers/Eigen/src/Eigenvalues/./HessenbergDecomposition.h
Gabrielle.o: headers/Eigen/src/Eigenvalues/EigenSolver.h
Gabrielle.o: headers/Eigen/src/Eigenvalues/./RealSchur.h
Gabrielle.o: headers/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h
Gabrielle.o: headers/Eigen/src/Eigenvalues/./Tridiagonalization.h
Gabrielle.o: headers/Eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h
Gabrielle.o: headers/Eigen/src/Eigenvalues/HessenbergDecomposition.h
Gabrielle.o: headers/Eigen/src/Eigenvalues/ComplexSchur.h
Gabrielle.o: headers/Eigen/src/Eigenvalues/ComplexEigenSolver.h
Gabrielle.o: headers/Eigen/src/Eigenvalues/./ComplexSchur.h
Gabrielle.o: headers/Eigen/src/Eigenvalues/RealQZ.h
Gabrielle.o: headers/Eigen/src/Eigenvalues/GeneralizedEigenSolver.h
Gabrielle.o: headers/Eigen/src/Eigenvalues/./RealQZ.h
Gabrielle.o: headers/Eigen/src/Eigenvalues/MatrixBaseEigenvalues.h
headers/Class.o: headers/Class.hpp headers/Eigen/Dense headers/Eigen/Core
headers/Class.o: headers/Eigen/src/Core/util/DisableStupidWarnings.h
headers/Class.o: headers/Eigen/src/Core/util/Macros.h
headers/Class.o: headers/Eigen/src/Core/util/MKL_support.h
headers/Class.o: headers/Eigen/src/Core/util/Constants.h
headers/Class.o: headers/Eigen/src/Core/util/Meta.h
headers/Class.o: headers/Eigen/src/Core/util/ForwardDeclarations.h
headers/Class.o: headers/Eigen/src/Core/util/StaticAssert.h
headers/Class.o: headers/Eigen/src/Core/util/XprHelper.h
headers/Class.o: headers/Eigen/src/Core/util/Memory.h
headers/Class.o: headers/Eigen/src/Core/NumTraits.h
headers/Class.o: headers/Eigen/src/Core/MathFunctions.h
headers/Class.o: headers/Eigen/src/Core/GenericPacketMath.h
headers/Class.o: headers/Eigen/src/Core/MathFunctionsImpl.h
headers/Class.o: headers/Eigen/src/Core/arch/Default/ConjHelper.h
headers/Class.o: headers/Eigen/src/Core/arch/CUDA/Half.h
headers/Class.o: headers/Eigen/src/Core/arch/CUDA/PacketMathHalf.h
headers/Class.o: headers/Eigen/src/Core/arch/CUDA/TypeCasting.h
headers/Class.o: headers/Eigen/src/Core/arch/Default/Settings.h
headers/Class.o: headers/Eigen/src/Core/functors/TernaryFunctors.h
headers/Class.o: headers/Eigen/src/Core/functors/BinaryFunctors.h
headers/Class.o: headers/Eigen/src/Core/functors/UnaryFunctors.h
headers/Class.o: headers/Eigen/src/Core/functors/NullaryFunctors.h
headers/Class.o: headers/Eigen/src/Core/functors/StlFunctors.h
headers/Class.o: headers/Eigen/src/Core/functors/AssignmentFunctors.h
headers/Class.o: headers/Eigen/src/Core/arch/CUDA/Complex.h
headers/Class.o: headers/Eigen/src/Core/IO.h
headers/Class.o: headers/Eigen/src/Core/DenseCoeffsBase.h
headers/Class.o: headers/Eigen/src/Core/DenseBase.h
headers/Class.o: headers/Eigen/src/plugins/BlockMethods.h
headers/Class.o: headers/Eigen/src/Core/MatrixBase.h
headers/Class.o: headers/Eigen/src/plugins/CommonCwiseUnaryOps.h
headers/Class.o: headers/Eigen/src/plugins/CommonCwiseBinaryOps.h
headers/Class.o: headers/Eigen/src/plugins/MatrixCwiseUnaryOps.h
headers/Class.o: headers/Eigen/src/plugins/MatrixCwiseBinaryOps.h
headers/Class.o: headers/Eigen/src/Core/EigenBase.h
headers/Class.o: headers/Eigen/src/Core/Product.h
headers/Class.o: headers/Eigen/src/Core/CoreEvaluators.h
headers/Class.o: headers/Eigen/src/Core/AssignEvaluator.h
headers/Class.o: headers/Eigen/src/Core/Assign.h
headers/Class.o: headers/Eigen/src/Core/ArrayBase.h
headers/Class.o: headers/Eigen/src/plugins/ArrayCwiseUnaryOps.h
headers/Class.o: headers/Eigen/src/plugins/ArrayCwiseBinaryOps.h
headers/Class.o: headers/Eigen/src/Core/util/BlasUtil.h
headers/Class.o: headers/Eigen/src/Core/DenseStorage.h
headers/Class.o: headers/Eigen/src/Core/NestByValue.h
headers/Class.o: headers/Eigen/src/Core/ReturnByValue.h
headers/Class.o: headers/Eigen/src/Core/NoAlias.h
headers/Class.o: headers/Eigen/src/Core/PlainObjectBase.h
headers/Class.o: headers/Eigen/src/Core/Matrix.h
headers/Class.o: headers/Eigen/src/Core/Array.h
headers/Class.o: headers/Eigen/src/Core/CwiseTernaryOp.h
headers/Class.o: headers/Eigen/src/Core/CwiseBinaryOp.h
headers/Class.o: headers/Eigen/src/Core/CwiseUnaryOp.h
headers/Class.o: headers/Eigen/src/Core/CwiseNullaryOp.h
headers/Class.o: headers/Eigen/src/Core/CwiseUnaryView.h
headers/Class.o: headers/Eigen/src/Core/SelfCwiseBinaryOp.h
headers/Class.o: headers/Eigen/src/Core/Dot.h
headers/Class.o: headers/Eigen/src/Core/StableNorm.h
headers/Class.o: headers/Eigen/src/Core/Stride.h
headers/Class.o: headers/Eigen/src/Core/MapBase.h
headers/Class.o: headers/Eigen/src/Core/Map.h headers/Eigen/src/Core/Ref.h
headers/Class.o: headers/Eigen/src/Core/Block.h
headers/Class.o: headers/Eigen/src/Core/VectorBlock.h
headers/Class.o: headers/Eigen/src/Core/Transpose.h
headers/Class.o: headers/Eigen/src/Core/DiagonalMatrix.h
headers/Class.o: headers/Eigen/src/Core/Diagonal.h
headers/Class.o: headers/Eigen/src/Core/DiagonalProduct.h
headers/Class.o: headers/Eigen/src/Core/Redux.h
headers/Class.o: headers/Eigen/src/Core/Visitor.h
headers/Class.o: headers/Eigen/src/Core/Fuzzy.h headers/Eigen/src/Core/Swap.h
headers/Class.o: headers/Eigen/src/Core/CommaInitializer.h
headers/Class.o: headers/Eigen/src/Core/GeneralProduct.h
headers/Class.o: headers/Eigen/src/Core/Solve.h
headers/Class.o: headers/Eigen/src/Core/Inverse.h
headers/Class.o: headers/Eigen/src/Core/SolverBase.h
headers/Class.o: headers/Eigen/src/Core/PermutationMatrix.h
headers/Class.o: headers/Eigen/src/Core/Transpositions.h
headers/Class.o: headers/Eigen/src/Core/TriangularMatrix.h
headers/Class.o: headers/Eigen/src/Core/SelfAdjointView.h
headers/Class.o: headers/Eigen/src/Core/products/GeneralBlockPanelKernel.h
headers/Class.o: headers/Eigen/src/Core/products/Parallelizer.h
headers/Class.o: headers/Eigen/src/Core/ProductEvaluators.h
headers/Class.o: headers/Eigen/src/Core/products/GeneralMatrixVector.h
headers/Class.o: headers/Eigen/src/Core/products/GeneralMatrixMatrix.h
headers/Class.o: headers/Eigen/src/Core/SolveTriangular.h
headers/Class.o: headers/Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h
headers/Class.o: headers/Eigen/src/Core/products/SelfadjointMatrixVector.h
headers/Class.o: headers/Eigen/src/Core/products/SelfadjointMatrixMatrix.h
headers/Class.o: headers/Eigen/src/Core/products/SelfadjointProduct.h
headers/Class.o: headers/Eigen/src/Core/products/SelfadjointRank2Update.h
headers/Class.o: headers/Eigen/src/Core/products/TriangularMatrixVector.h
headers/Class.o: headers/Eigen/src/Core/products/TriangularMatrixMatrix.h
headers/Class.o: headers/Eigen/src/Core/products/TriangularSolverMatrix.h
headers/Class.o: headers/Eigen/src/Core/products/TriangularSolverVector.h
headers/Class.o: headers/Eigen/src/Core/BandMatrix.h
headers/Class.o: headers/Eigen/src/Core/CoreIterators.h
headers/Class.o: headers/Eigen/src/Core/ConditionEstimator.h
headers/Class.o: headers/Eigen/src/Core/BooleanRedux.h
headers/Class.o: headers/Eigen/src/Core/Select.h
headers/Class.o: headers/Eigen/src/Core/VectorwiseOp.h
headers/Class.o: headers/Eigen/src/Core/Random.h
headers/Class.o: headers/Eigen/src/Core/Replicate.h
headers/Class.o: headers/Eigen/src/Core/Reverse.h
headers/Class.o: headers/Eigen/src/Core/ArrayWrapper.h
headers/Class.o: headers/Eigen/src/Core/GlobalFunctions.h
headers/Class.o: headers/Eigen/src/Core/util/ReenableStupidWarnings.h
headers/Class.o: headers/Eigen/LU headers/Eigen/src/misc/Kernel.h
headers/Class.o: headers/Eigen/src/misc/Image.h
headers/Class.o: headers/Eigen/src/LU/FullPivLU.h
headers/Class.o: headers/Eigen/src/LU/PartialPivLU.h
headers/Class.o: headers/Eigen/src/LU/Determinant.h
headers/Class.o: headers/Eigen/src/LU/InverseImpl.h headers/Eigen/Cholesky
headers/Class.o: headers/Eigen/Jacobi headers/Eigen/src/Jacobi/Jacobi.h
headers/Class.o: headers/Eigen/src/Cholesky/LLT.h
headers/Class.o: headers/Eigen/src/Cholesky/LDLT.h headers/Eigen/QR
headers/Class.o: headers/Eigen/Householder
headers/Class.o: headers/Eigen/src/Householder/Householder.h
headers/Class.o: headers/Eigen/src/Householder/HouseholderSequence.h
headers/Class.o: headers/Eigen/src/Householder/BlockHouseholder.h
headers/Class.o: headers/Eigen/src/QR/HouseholderQR.h
headers/Class.o: headers/Eigen/src/QR/FullPivHouseholderQR.h
headers/Class.o: headers/Eigen/src/QR/ColPivHouseholderQR.h
headers/Class.o: headers/Eigen/src/QR/CompleteOrthogonalDecomposition.h
headers/Class.o: headers/Eigen/SVD headers/Eigen/src/misc/RealSvd2x2.h
headers/Class.o: headers/Eigen/src/SVD/UpperBidiagonalization.h
headers/Class.o: headers/Eigen/src/SVD/SVDBase.h
headers/Class.o: headers/Eigen/src/SVD/JacobiSVD.h
headers/Class.o: headers/Eigen/src/SVD/BDCSVD.h headers/Eigen/Geometry
headers/Class.o: headers/Eigen/src/Geometry/OrthoMethods.h
headers/Class.o: headers/Eigen/src/Geometry/EulerAngles.h
headers/Class.o: headers/Eigen/src/Geometry/Homogeneous.h
headers/Class.o: headers/Eigen/src/Geometry/RotationBase.h
headers/Class.o: headers/Eigen/src/Geometry/Rotation2D.h
headers/Class.o: headers/Eigen/src/Geometry/Quaternion.h
headers/Class.o: headers/Eigen/src/Geometry/AngleAxis.h
headers/Class.o: headers/Eigen/src/Geometry/Transform.h
headers/Class.o: headers/Eigen/src/Geometry/Translation.h
headers/Class.o: headers/Eigen/src/Geometry/Scaling.h
headers/Class.o: headers/Eigen/src/Geometry/Hyperplane.h
headers/Class.o: headers/Eigen/src/Geometry/ParametrizedLine.h
headers/Class.o: headers/Eigen/src/Geometry/AlignedBox.h
headers/Class.o: headers/Eigen/src/Geometry/Umeyama.h
headers/Class.o: headers/Eigen/Eigenvalues
headers/Class.o: headers/Eigen/src/Eigenvalues/Tridiagonalization.h
headers/Class.o: headers/Eigen/src/Eigenvalues/RealSchur.h
headers/Class.o: headers/Eigen/src/Eigenvalues/./HessenbergDecomposition.h
headers/Class.o: headers/Eigen/src/Eigenvalues/EigenSolver.h
headers/Class.o: headers/Eigen/src/Eigenvalues/./RealSchur.h
headers/Class.o: headers/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h
headers/Class.o: headers/Eigen/src/Eigenvalues/./Tridiagonalization.h
headers/Class.o: headers/Eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h
headers/Class.o: headers/Eigen/src/Eigenvalues/HessenbergDecomposition.h
headers/Class.o: headers/Eigen/src/Eigenvalues/ComplexSchur.h
headers/Class.o: headers/Eigen/src/Eigenvalues/ComplexEigenSolver.h
headers/Class.o: headers/Eigen/src/Eigenvalues/./ComplexSchur.h
headers/Class.o: headers/Eigen/src/Eigenvalues/RealQZ.h
headers/Class.o: headers/Eigen/src/Eigenvalues/GeneralizedEigenSolver.h
headers/Class.o: headers/Eigen/src/Eigenvalues/./RealQZ.h
headers/Class.o: headers/Eigen/src/Eigenvalues/MatrixBaseEigenvalues.h
headers/Methods.o: headers/Methods.hpp headers/Class.hpp headers/Eigen/Dense
headers/Methods.o: headers/Eigen/Core
headers/Methods.o: headers/Eigen/src/Core/util/DisableStupidWarnings.h
headers/Methods.o: headers/Eigen/src/Core/util/Macros.h
headers/Methods.o: headers/Eigen/src/Core/util/MKL_support.h
headers/Methods.o: headers/Eigen/src/Core/util/Constants.h
headers/Methods.o: headers/Eigen/src/Core/util/Meta.h
headers/Methods.o: headers/Eigen/src/Core/util/ForwardDeclarations.h
headers/Methods.o: headers/Eigen/src/Core/util/StaticAssert.h
headers/Methods.o: headers/Eigen/src/Core/util/XprHelper.h
headers/Methods.o: headers/Eigen/src/Core/util/Memory.h
headers/Methods.o: headers/Eigen/src/Core/NumTraits.h
headers/Methods.o: headers/Eigen/src/Core/MathFunctions.h
headers/Methods.o: headers/Eigen/src/Core/GenericPacketMath.h
headers/Methods.o: headers/Eigen/src/Core/MathFunctionsImpl.h
headers/Methods.o: headers/Eigen/src/Core/arch/Default/ConjHelper.h
headers/Methods.o: headers/Eigen/src/Core/arch/CUDA/Half.h
headers/Methods.o: headers/Eigen/src/Core/arch/CUDA/PacketMathHalf.h
headers/Methods.o: headers/Eigen/src/Core/arch/CUDA/TypeCasting.h
headers/Methods.o: headers/Eigen/src/Core/arch/Default/Settings.h
headers/Methods.o: headers/Eigen/src/Core/functors/TernaryFunctors.h
headers/Methods.o: headers/Eigen/src/Core/functors/BinaryFunctors.h
headers/Methods.o: headers/Eigen/src/Core/functors/UnaryFunctors.h
headers/Methods.o: headers/Eigen/src/Core/functors/NullaryFunctors.h
headers/Methods.o: headers/Eigen/src/Core/functors/StlFunctors.h
headers/Methods.o: headers/Eigen/src/Core/functors/AssignmentFunctors.h
headers/Methods.o: headers/Eigen/src/Core/arch/CUDA/Complex.h
headers/Methods.o: headers/Eigen/src/Core/IO.h
headers/Methods.o: headers/Eigen/src/Core/DenseCoeffsBase.h
headers/Methods.o: headers/Eigen/src/Core/DenseBase.h
headers/Methods.o: headers/Eigen/src/plugins/BlockMethods.h
headers/Methods.o: headers/Eigen/src/Core/MatrixBase.h
headers/Methods.o: headers/Eigen/src/plugins/CommonCwiseUnaryOps.h
headers/Methods.o: headers/Eigen/src/plugins/CommonCwiseBinaryOps.h
headers/Methods.o: headers/Eigen/src/plugins/MatrixCwiseUnaryOps.h
headers/Methods.o: headers/Eigen/src/plugins/MatrixCwiseBinaryOps.h
headers/Methods.o: headers/Eigen/src/Core/EigenBase.h
headers/Methods.o: headers/Eigen/src/Core/Product.h
headers/Methods.o: headers/Eigen/src/Core/CoreEvaluators.h
headers/Methods.o: headers/Eigen/src/Core/AssignEvaluator.h
headers/Methods.o: headers/Eigen/src/Core/Assign.h
headers/Methods.o: headers/Eigen/src/Core/ArrayBase.h
headers/Methods.o: headers/Eigen/src/plugins/ArrayCwiseUnaryOps.h
headers/Methods.o: headers/Eigen/src/plugins/ArrayCwiseBinaryOps.h
headers/Methods.o: headers/Eigen/src/Core/util/BlasUtil.h
headers/Methods.o: headers/Eigen/src/Core/DenseStorage.h
headers/Methods.o: headers/Eigen/src/Core/NestByValue.h
headers/Methods.o: headers/Eigen/src/Core/ReturnByValue.h
headers/Methods.o: headers/Eigen/src/Core/NoAlias.h
headers/Methods.o: headers/Eigen/src/Core/PlainObjectBase.h
headers/Methods.o: headers/Eigen/src/Core/Matrix.h
headers/Methods.o: headers/Eigen/src/Core/Array.h
headers/Methods.o: headers/Eigen/src/Core/CwiseTernaryOp.h
headers/Methods.o: headers/Eigen/src/Core/CwiseBinaryOp.h
headers/Methods.o: headers/Eigen/src/Core/CwiseUnaryOp.h
headers/Methods.o: headers/Eigen/src/Core/CwiseNullaryOp.h
headers/Methods.o: headers/Eigen/src/Core/CwiseUnaryView.h
headers/Methods.o: headers/Eigen/src/Core/SelfCwiseBinaryOp.h
headers/Methods.o: headers/Eigen/src/Core/Dot.h
headers/Methods.o: headers/Eigen/src/Core/StableNorm.h
headers/Methods.o: headers/Eigen/src/Core/Stride.h
headers/Methods.o: headers/Eigen/src/Core/MapBase.h
headers/Methods.o: headers/Eigen/src/Core/Map.h headers/Eigen/src/Core/Ref.h
headers/Methods.o: headers/Eigen/src/Core/Block.h
headers/Methods.o: headers/Eigen/src/Core/VectorBlock.h
headers/Methods.o: headers/Eigen/src/Core/Transpose.h
headers/Methods.o: headers/Eigen/src/Core/DiagonalMatrix.h
headers/Methods.o: headers/Eigen/src/Core/Diagonal.h
headers/Methods.o: headers/Eigen/src/Core/DiagonalProduct.h
headers/Methods.o: headers/Eigen/src/Core/Redux.h
headers/Methods.o: headers/Eigen/src/Core/Visitor.h
headers/Methods.o: headers/Eigen/src/Core/Fuzzy.h
headers/Methods.o: headers/Eigen/src/Core/Swap.h
headers/Methods.o: headers/Eigen/src/Core/CommaInitializer.h
headers/Methods.o: headers/Eigen/src/Core/GeneralProduct.h
headers/Methods.o: headers/Eigen/src/Core/Solve.h
headers/Methods.o: headers/Eigen/src/Core/Inverse.h
headers/Methods.o: headers/Eigen/src/Core/SolverBase.h
headers/Methods.o: headers/Eigen/src/Core/PermutationMatrix.h
headers/Methods.o: headers/Eigen/src/Core/Transpositions.h
headers/Methods.o: headers/Eigen/src/Core/TriangularMatrix.h
headers/Methods.o: headers/Eigen/src/Core/SelfAdjointView.h
headers/Methods.o: headers/Eigen/src/Core/products/GeneralBlockPanelKernel.h
headers/Methods.o: headers/Eigen/src/Core/products/Parallelizer.h
headers/Methods.o: headers/Eigen/src/Core/ProductEvaluators.h
headers/Methods.o: headers/Eigen/src/Core/products/GeneralMatrixVector.h
headers/Methods.o: headers/Eigen/src/Core/products/GeneralMatrixMatrix.h
headers/Methods.o: headers/Eigen/src/Core/SolveTriangular.h
headers/Methods.o: headers/Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h
headers/Methods.o: headers/Eigen/src/Core/products/SelfadjointMatrixVector.h
headers/Methods.o: headers/Eigen/src/Core/products/SelfadjointMatrixMatrix.h
headers/Methods.o: headers/Eigen/src/Core/products/SelfadjointProduct.h
headers/Methods.o: headers/Eigen/src/Core/products/SelfadjointRank2Update.h
headers/Methods.o: headers/Eigen/src/Core/products/TriangularMatrixVector.h
headers/Methods.o: headers/Eigen/src/Core/products/TriangularMatrixMatrix.h
headers/Methods.o: headers/Eigen/src/Core/products/TriangularSolverMatrix.h
headers/Methods.o: headers/Eigen/src/Core/products/TriangularSolverVector.h
headers/Methods.o: headers/Eigen/src/Core/BandMatrix.h
headers/Methods.o: headers/Eigen/src/Core/CoreIterators.h
headers/Methods.o: headers/Eigen/src/Core/ConditionEstimator.h
headers/Methods.o: headers/Eigen/src/Core/BooleanRedux.h
headers/Methods.o: headers/Eigen/src/Core/Select.h
headers/Methods.o: headers/Eigen/src/Core/VectorwiseOp.h
headers/Methods.o: headers/Eigen/src/Core/Random.h
headers/Methods.o: headers/Eigen/src/Core/Replicate.h
headers/Methods.o: headers/Eigen/src/Core/Reverse.h
headers/Methods.o: headers/Eigen/src/Core/ArrayWrapper.h
headers/Methods.o: headers/Eigen/src/Core/GlobalFunctions.h
headers/Methods.o: headers/Eigen/src/Core/util/ReenableStupidWarnings.h
headers/Methods.o: headers/Eigen/LU headers/Eigen/src/misc/Kernel.h
headers/Methods.o: headers/Eigen/src/misc/Image.h
headers/Methods.o: headers/Eigen/src/LU/FullPivLU.h
headers/Methods.o: headers/Eigen/src/LU/PartialPivLU.h
headers/Methods.o: headers/Eigen/src/LU/Determinant.h
headers/Methods.o: headers/Eigen/src/LU/InverseImpl.h headers/Eigen/Cholesky
headers/Methods.o: headers/Eigen/Jacobi headers/Eigen/src/Jacobi/Jacobi.h
headers/Methods.o: headers/Eigen/src/Cholesky/LLT.h
headers/Methods.o: headers/Eigen/src/Cholesky/LDLT.h headers/Eigen/QR
headers/Methods.o: headers/Eigen/Householder
headers/Methods.o: headers/Eigen/src/Householder/Householder.h
headers/Methods.o: headers/Eigen/src/Householder/HouseholderSequence.h
headers/Methods.o: headers/Eigen/src/Householder/BlockHouseholder.h
headers/Methods.o: headers/Eigen/src/QR/HouseholderQR.h
headers/Methods.o: headers/Eigen/src/QR/FullPivHouseholderQR.h
headers/Methods.o: headers/Eigen/src/QR/ColPivHouseholderQR.h
headers/Methods.o: headers/Eigen/src/QR/CompleteOrthogonalDecomposition.h
headers/Methods.o: headers/Eigen/SVD headers/Eigen/src/misc/RealSvd2x2.h
headers/Methods.o: headers/Eigen/src/SVD/UpperBidiagonalization.h
headers/Methods.o: headers/Eigen/src/SVD/SVDBase.h
headers/Methods.o: headers/Eigen/src/SVD/JacobiSVD.h
headers/Methods.o: headers/Eigen/src/SVD/BDCSVD.h headers/Eigen/Geometry
headers/Methods.o: headers/Eigen/src/Geometry/OrthoMethods.h
headers/Methods.o: headers/Eigen/src/Geometry/EulerAngles.h
headers/Methods.o: headers/Eigen/src/Geometry/Homogeneous.h
headers/Methods.o: headers/Eigen/src/Geometry/RotationBase.h
headers/Methods.o: headers/Eigen/src/Geometry/Rotation2D.h
headers/Methods.o: headers/Eigen/src/Geometry/Quaternion.h
headers/Methods.o: headers/Eigen/src/Geometry/AngleAxis.h
headers/Methods.o: headers/Eigen/src/Geometry/Transform.h
headers/Methods.o: headers/Eigen/src/Geometry/Translation.h
headers/Methods.o: headers/Eigen/src/Geometry/Scaling.h
headers/Methods.o: headers/Eigen/src/Geometry/Hyperplane.h
headers/Methods.o: headers/Eigen/src/Geometry/ParametrizedLine.h
headers/Methods.o: headers/Eigen/src/Geometry/AlignedBox.h
headers/Methods.o: headers/Eigen/src/Geometry/Umeyama.h
headers/Methods.o: headers/Eigen/Eigenvalues
headers/Methods.o: headers/Eigen/src/Eigenvalues/Tridiagonalization.h
headers/Methods.o: headers/Eigen/src/Eigenvalues/RealSchur.h
headers/Methods.o: headers/Eigen/src/Eigenvalues/./HessenbergDecomposition.h
headers/Methods.o: headers/Eigen/src/Eigenvalues/EigenSolver.h
headers/Methods.o: headers/Eigen/src/Eigenvalues/./RealSchur.h
headers/Methods.o: headers/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h
headers/Methods.o: headers/Eigen/src/Eigenvalues/./Tridiagonalization.h
headers/Methods.o: headers/Eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h
headers/Methods.o: headers/Eigen/src/Eigenvalues/HessenbergDecomposition.h
headers/Methods.o: headers/Eigen/src/Eigenvalues/ComplexSchur.h
headers/Methods.o: headers/Eigen/src/Eigenvalues/ComplexEigenSolver.h
headers/Methods.o: headers/Eigen/src/Eigenvalues/./ComplexSchur.h
headers/Methods.o: headers/Eigen/src/Eigenvalues/RealQZ.h
headers/Methods.o: headers/Eigen/src/Eigenvalues/GeneralizedEigenSolver.h
headers/Methods.o: headers/Eigen/src/Eigenvalues/./RealQZ.h
headers/Methods.o: headers/Eigen/src/Eigenvalues/MatrixBaseEigenvalues.h
